#!/usr/bin/env python3

# http://python-gtk-3-tutorial.readthedocs.org/en/latest/layout.html

from gi.repository import Gtk, Gdk
import os
import kano_settings.set_intro as set_intro
import kano_settings.set_email as set_email
import kano_settings.set_keyboard as set_keyboard
import kano_settings.set_audio as set_audio
import kano_settings.set_display as set_display
import kano_settings.set_wifi as set_wifi
import kano_settings.config_file as config_file
import kano_settings.components.top_bar as top_bar
import kano_settings.components.apply_changes as apply_changes
import kano_settings.components.icons as icons
import kano_settings.components.menu_button as menu_button
import kano_settings.constants as constants
import kano_settings.components.first_run as first_run
import kano_settings.components.default_intro as default_intro

win = None
MAX_STATE = 6

# Window class
class MainWindow(Gtk.Window):
    grid = None
    box = None
    state = 0

    def __init__(self):
        global grid, box, win

        self.last_level_visited = 0

        WINDOW_WIDTH = 600
        WINDOW_HEIGHT = 380

        # Create main window
        Gtk.Window.__init__(self, title="Kano-Settings")
        # Remove decoration
        self.set_decorated(False)

        self.set_size_request(WINDOW_WIDTH, WINDOW_HEIGHT)

        # Main container of the window
        self.grid = Gtk.Grid()

        # Content that changes between levels
        self.changable_content = Gtk.Box(orientation=Gtk.Orientation.VERTICAL, spacing=6)
        self.changable_content.props.halign = Gtk.Align.CENTER

        self.top_bar = top_bar.Top_bar()

        # Init
        if config_file.read_from_file('Completed') == "1":
            self.apply_changes = apply_changes.Apply(True)
            self.apply_changes.text.set_text("Get started")
            # Order of icon and writing changes 
            self.apply_changes.image.set_from_pixbuf(icons.Icons(5).subpixel)
            
            print("Settings has been completed before")

            self.run_through = default_intro.Default_Intro(self)
            #self.default_intro = Gtk.Table(3, 2, True)
            #self.default_intro_init()
            #Need new functions here
            self.top_bar.next_button.connect("clicked", self.run_through.on_next)
            self.top_bar.prev_button.connect("clicked", self.run_through.on_prev)
            self.apply_changes.button.connect('clicked', self.run_through.update)

        else:
            print("Settings has NOT been completed before")
            # Order of icon and writing changes 
            self.apply_changes = apply_changes.Apply(False)
            # self.apply_changes.text.set_text("Get started")
            self.run_through = first_run.First_Run(self)

            self.apply_changes.button.connect('clicked', self.run_through.update_and_next)
            set_intro.activate(self, self.changable_content, self.apply_changes.button)
            self.top_bar.prev_button.connect("clicked", self.run_through.on_prev)
            self.top_bar.next_button.connect("clicked", self.run_through.on_next)

        self.grid.attach(self.top_bar.background, 0, 0, 1, 1)
        self.grid.attach(self.changable_content, 0, 2, 1, 1)
        self.grid.set_row_spacing(0)
        self.add(self.grid)



"""    # Takes you back to the introduction screen (on pressing prev button)
    def back_to_intro(self, arg2):
        # save last level?
        for i in self.changable_content.get_children():
            self.changable_content.remove(i)

        self.default_intro_text()

        self.changable_content.pack_start(self.default_intro, True, True, 0)"""

    # Initialises the default into screen
"""    def default_intro_init(self):
        global grid, box, state

        for i in self.changable_content.get_children():
            self.changable_content.remove(i)

        # Read from config file.
        # If value is 1:
        self.default_intro = Gtk.Table(3, 2, True)

        buttons = []
        self.labels = []

        #names at top of file
        for x in range(len(names)):
            info = config_file.read_from_file(names[x])
            self.menu_button = menu_button.Menu_button(names[x], info)
            self.labels.append(self.menu_button.description)

            self.menu_button.button.state = x
            self.menu_button.button.connect("clicked", self.go_to_level)
            buttons.append(self.menu_button.button)

        # Attach to table
        self.default_intro.attach(buttons[0], 0, 1, 0, 1, Gtk.AttachOptions.EXPAND, Gtk.AttachOptions.EXPAND, 5, 5)
        self.default_intro.attach(buttons[1], 0, 1, 1, 2, Gtk.AttachOptions.EXPAND, Gtk.AttachOptions.EXPAND, 5, 5)
        self.default_intro.attach(buttons[2], 0, 1, 2, 3, Gtk.AttachOptions.EXPAND, Gtk.AttachOptions.EXPAND, 5, 5)
        self.default_intro.attach(buttons[3], 1, 2, 0, 1, Gtk.AttachOptions.EXPAND, Gtk.AttachOptions.EXPAND, 5, 5)
        self.default_intro.attach(buttons[4], 1, 2, 1, 2, Gtk.AttachOptions.EXPAND, Gtk.AttachOptions.EXPAND, 5, 5)

        self.default_intro.set_size_request(450, 100)

        self.changable_content.pack_start(self.default_intro, True, True, 0)"""


"""    # This is to update the introdction text, so that if the settings are modified and then we go back to the
    # intro screen, the latest information is shown
    def default_intro_text(self):
        for x in range(len(custom_info)):
            config_file.read_from_file(custom_info[x])
            self.labels[x].set_text(str(config_file.read_from_file(custom_info[x])))

    # This updates the current level.
    def update(self, widget):
        returnValue = self.state_to_widget(self.state).apply_changes(widget)
        if returnValue == -1:
            return"""

"""    # Updates the current level and goes to the next (when clicking Next -> button in first run through levels).
    def update_and_next(self, widget):
        returnValue = self.state_to_widget(self.state).apply_changes(widget)
        if returnValue == -1:
            return

        self.on_next(widget)"""

"""    # When clicking next in the default intro screen - takes you to the last level you visited
    def default_next(self, widget):
        if self.last_level_visited == 0:
            return

        for i in self.changable_content.get_children():
            self.changable_content.remove(i)
        
        self.state_to_widget(self.last_level_visited).activate(self, self.changable_content, self.apply_changes) 
        self.last_level_visited = self.state   
        win.show_all()"""

"""    # When clicking next arrow button on first run through    
    def on_next(self, widget):
        global grid, box, state

        # Update current state
        self.state = (self.state + 1)
        # If we've clicked on the finished
        if self.state == MAX_STATE:
            # Write to config file to say we've completed the level.
            config_file.replace_setting("Completed", "1")
            # Finished, so close window
            close_window()
            return

        # Remove element in the dynamic box
        for i in self.changable_content.get_children():
            self.changable_content.remove(i)

        # Call next state
        self.state_to_widget(self.state).activate(self, self.changable_content, self.apply_changes)

        # Change label on Apply Changes button
        if self.state == MAX_STATE -1:
            self.apply_changes.text.set_text("Finish!")
        elif self.state > 0:
            self.apply_changes.text.set_text("Next")
        else:
            self.apply_changes.text.set_text("Get started")
        # Refresh window
        win.show_all()"""

"""    # Takes you back to the introduction screen (on pressing prev button)
    def back_to_intro(self, arg2):
        # save last level?
        for i in self.changable_content.get_children():
            self.changable_content.remove(i)

        self.default_intro_text()

        self.changable_content.pack_start(self.default_intro, True, True, 0)"""

"""    # When clicking previous arrow on first run through
    def on_prev(self, widget):
         # Update current state
        self.state = (self.state - 1)
        # Check we're in a valid state
        if self.state == -1:
            self.state = 0
            return;

        # Remove element in the dynamic box
        for i in self.changable_content.get_children():
            self.changable_content.remove(i)
       
        # Call next state
        self.state_to_widget(self.state).activate(self, self.changable_content, self.apply_changes)

        # Change label on Apply Changes button
        if self.state == MAX_STATE -1:
            self.apply_changes.text.set_text("Finish!")
        elif self.state > 0:
            self.apply_changes.text.set_text("Next")
        else:
            self.apply_changes.text.set_text("Get started")
        # Refresh window
        win.show_all()
"""
"""    # On clicing a level button on default intro screen
    def go_to_level(self, widget):
        # Remove element in the dynamic box
        for i in self.changable_content.get_children():
            self.changable_content.remove(i)
        # Update current state
        self.state = widget.state + 1
        # Record this level so we can go back to it
        self.last_level_visited = self.state
        # Call next state
        self.state_to_widget(self.state).activate(self, self.changable_content, self.apply_changes)
        # Refresh window
        win.show_all()"""


"""    def state_to_widget(self, x):
        return {
            0: set_intro,
            1: set_email,
            2: set_keyboard,
            3: set_audio,
            4: set_wifi,
            5: set_display,
        }[x]
"""

def main():
    global win
    # Create style sheet
    cssProvider = Gtk.CssProvider()
    #cssProvider.load_from_path('/usr/lib/python3/dist-packages/kano_settings/style.css')
    cssProvider.load_from_path(constants.files + 'style.css')
    screen = Gdk.Screen.get_default()
    styleContext = Gtk.StyleContext()
    styleContext.add_provider_for_screen(screen, cssProvider,
                                     Gtk.STYLE_PROVIDER_PRIORITY_USER)

    # Create windown
    win = MainWindow()
    # Link delete event
    win.connect("delete-event", close_window)
    # Display window
    win.show_all()

    # start the GTK+ processing loop
    Gtk.main()

# On closing window, will alert if any of the listed booleans are True
def close_window(event="delete-event", button=win):

    if set_audio.reboot or set_display.reboot:
        #Bring in message dialog box
        dialog = Gtk.MessageDialog(button, 0, Gtk.MessageType.INFO,
            Gtk.ButtonsType.OK, "So you know...")
        dialog.format_secondary_text(
            "..you will need to reboot to see all your changes")
        response = dialog.run()
        print("INFO dialog closed")

        if response == Gtk.ResponseType.OK:
            dialog.destroy() 
            Gtk.main_quit()
            return
        else:
            dialog.destroy()
    else:
        Gtk.main_quit()


if __name__ == "__main__":
    # Print system python version for debugging purposes only
    print(str(Gtk.get_major_version()) + "." + str(Gtk.get_minor_version()) + "." + str(Gtk.get_micro_version()))

    if os.environ['LOGNAME'] != 'root':
        exit("Error: kano-settings must be executed with root privileges")

    main()