#!/bin/sh

### BEGIN INIT INFO
# Provides:         kano-hdmi
# Required-Start:
# Required-Stop:
# Default-Start:    2
# Default-Stop:
### END INIT INFO

skip=`json-get /boot/init.conf set-kano-hdmi.skip`
if [ "$skip" = "True" ]; then
    exit 0
else
    /usr/bin/set-kano-hdmi
fi
