#!/bin/sh

### BEGIN INIT INFO
# Provides:         kano-settings
# Required-Start:   $local_fs
# Required-Stop:
# X-Start-Before:   lightdm
# Default-Start:    2
# Default-Stop:
### END INIT INFO

. /lib/lsb/init-functions
. gettext.sh
export TEXTDOMAIN="kano-settings"

case "$1" in
    start)
        # Display a welcome message to the bootup terminal
        eval_gettext "Get ready... Kano is starting up." > /dev/tty1

        # A new line, to position the shell prompt underneath
        echo "" > /dev/tty1

        systemctl --quiet is-active kano-safe-mode-requested.target
        sm_req=$?
        systemctl --quiet is-active kano-safe-mode.target
        sm=$?

        # Check that Safe Mode was not requested and that this is
        # not a Safe Mode boot.
        if [ $sm_req -ne 0 ] && [ $sm -ne 0 ]; then

            # If you have a special screen or hardware that needs custom
            # config.txt settings, create this sentinel file to avoid system
            # reboots and eventual black screens.
            onboot_sentinel_file="/boot/no-config-writes"
            if [ ! -f "$onboot_sentinel_file" ]; then
                log_action_begin_msg "Running kano-settings-onboot"
                /usr/bin/kano-settings-onboot
            else
                log_action_begin_msg "Disabling kano-settings-onboot due to $onboot_sentinel_file"
            fi
        fi

        # Fix for noobs:
        /sbin/setcap cap_net_raw+ep /bin/ping6 || true
        /sbin/setcap cap_net_raw+ep /bin/ping || true
        /sbin/setcap cap_net_raw+ep /usr/bin/fping6 || true
        /sbin/setcap cap_net_raw+ep /usr/bin/fping || true
        /sbin/setcap cap_dac_override,cap_sys_ptrace+ep /usr/bin/systemd-detect-virt || true
        log_action_end_msg $?
    ;;
    stop)
    ;;
    restart|reload|force-reload|status)
        echo "Error: argument '$1' not supported" >&2
        exit 3
    ;;
    *)
      echo "Usage: kano-settings [start|stop]" >&2
      exit 3
      ;;
esac

