#!/bin/sh

### BEGIN INIT INFO
# Provides:         kano-safeboot
# Required-Start:   $local_fs
# Required-Stop:
# X-Start-Before:   
# Default-Start:    2
# Default-Stop:
### END INIT INFO

. /lib/lsb/init-functions

case "$1" in
    start)
	log_action_begin_msg "Checking for kano-safeboot-mode"
	/usr/bin/kano-safeboot-mode
	log_action_end_msg $?
	;;
    stop)
	;;
    restart|reload|force-reload|status)
        echo "Error: argument '$1' not supported" >&2
        exit 3
	;;
    *)
      echo "Usage: kano-safeboot [start|stop]" >&2
      exit 3
      ;;
esac

