#!/bin/sh

### BEGIN INIT INFO
# Provides:         kano-settings
# Required-Start:   $local_fs
# Required-Stop:
# X-Start-Before:   lightdm
# Default-Start:    2
# Default-Stop:
### END INIT INFO

. /lib/lsb/init-functions

case "$1" in
    start)
        # Display a welcome message to the bootup terminal
	gettext kano-settings "Get ready... Kano is starting up." > /dev/tty1

        # If Dashboard Onboot is installed (soft dependency),
        # call him now. He enforces the kit to always go to Dashboard/Greeter.
        if [ -x "/usr/bin/kano-dashboard-onboot" ]; then
            /usr/bin/kano-dashboard-onboot
        fi

	log_action_begin_msg "Running kano-settings-onboot"
	/usr/bin/kano-settings-onboot
        # Fix for noobs:
        /sbin/setcap cap_net_raw+ep /bin/ping6 || true
        /sbin/setcap cap_net_raw+ep /bin/ping || true
        /sbin/setcap cap_net_raw+ep /usr/bin/fping6 || true
        /sbin/setcap cap_net_raw+ep /usr/bin/fping || true
        /sbin/setcap cap_dac_override,cap_sys_ptrace+ep /usr/bin/systemd-detect-virt || true
	log_action_end_msg $?
	;;
    stop)
	;;
    restart|reload|force-reload|status)
        echo "Error: argument '$1' not supported" >&2
        exit 3
	;;
    *)
      echo "Usage: kano-settings [start|stop]" >&2
      exit 3
      ;;
esac

