#!/bin/sh
#
# kano-reboot-clear
#
# Copyright (C) 2016 Kano Computing Ltd.
# License: http://www.gnu.org/licenses/gpl-2.0.txt GNU General Public License v2
#


### BEGIN INIT INFO
# Provides:         kano-reboot-clear
# Required-Start:   $local_fs $all kano-settings
# Required-Stop:
# X-Start-Before:
# Default-Start:    2 3 4 5
# Default-Stop:
### END INIT INFO


# This file clears reboot sentinels, which are used by kano-checked-reboot
# to avoid indefinite rebooting.
# The idea of this script is to clear the sentinels only when it is reasonly clear that we have
# bootted stably.
#
# Frustratingly systemd ignores the $all dependency, so we additionally depend on all
# scripts we know contain reboot commands and then wait for an additional period to be safe.

. /lib/lsb/init-functions

case "$1" in
    start)
        # Display a welcome message to the bootup terminal
	log_action_begin_msg "Running kano-reboot-clear"
	(
	    sleep 333 ;	rm -rf /boot/kano_reboots
	) &
	log_action_end_msg $?
	;;
    stop)
	;;
    restart|reload|force-reload|status)
        echo "Error: argument '$1' not supported" >&2
        exit 3
	;;
    *)
      echo "Usage: kano-reboot-clear [start|stop]" >&2
      exit 3
      ;;
esac

