bin/kano-connect usr/bin
bin/kano-wifi usr/bin
bin/kano-wifi-gui usr/bin

kano_wifi_gui/* usr/lib/python2.7/dist-packages/kano_wifi_gui

icon/widget-no-internet.png /usr/share/kano-settings/icon
icon/widget-wifi.png /usr/share/kano-settings/icon

lxpanel-plugin-internet/kano_internet.so usr/lib/arm-linux-gnueabihf/lxpanel/plugins/

etc/modprobe.d /usr/share/kano-network/etc
etc/network /usr/share/kano-network/etc

media/kano-connect/* /usr/share/kano-connect/media
