#!/bin/bash

# kanux_crontab
#
# Copyright (C) 2014 Kano Computing Ltd.
# License: http://www.gnu.org/licenses/gpl-2.0.txt GNU General Public License v2

SHELL=/bin/sh
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
MAILTO=""

00 * * * * root /usr/bin/rdate -4 -u -v -c -n $(cat /etc/timeserver.conf)
